# © Copyright 2024 Hewlett Packard Enterprise Development LP
# Create a secret for the hpe-cosi-driver user
---
apiVersion: v1
kind: Secret
metadata:
  name: cosi-user-secret-1
  namespace: default
type: Opaque
stringData:
  accessKey: S3_USER_NAME
  secretKey: S3_PASSWORD
  endpoint: http://192.168.1.100:8080
  glcpUserClientId: GLCP_USER_ID
  glcpUserSecretKey: GLCP_USER_KEY
  dsccZone: us1.data.cloud.hpe.com
  clusterSerialNumber: XX0000000000XX